### ISSUE TITLE
triggering issue

### ISSUE THREAD

**Issue by WALIII** [gardner-lab/video-capture#8]
The super secret V1.0 has triggering problems- I couldn't get it to trigger!

<3
-W

**Comment by nathanntg** [comment]
Did you change the preference for triggering to "song detector"? The default is Arduino triggering, since that is how most other people will use it. 

I'll test everything tomorrow too, just to confirm.

**Comment by nathanntg** [comment]
Yeah, the song triggering does seem to be working once the preferences are set to use the song detector. Let me know if you are still having problems getting it to trigger.

![napkin 02-24-16 8 28 26 am](https://cloud.githubusercontent.com/assets/194728/13286631/acb52b26-dad0-11e5-9ec7-7fac2a782a8b.png)

**Comment by WALIII** [comment]
I meant the arduino triggering- the song trigger works great, but I couldn't get the arduino trigger to work for some reason

**Comment by WALIII** [comment]
It does work in the most recent release, so I know its not a hardware issue

**Comment by nathanntg** [comment]
Okay, let me investigate some more.

**Comment by nathanntg** [comment]
Hmm, I am still having trouble recreating this. I was able to capture video using the Arduino trigger as well. We should continue testing once you return to figure out what is causing the issues.

**Comment by nathanntg** [comment]
I found the issue! And another issue as well. Stay tuned.

**Comment by nathanntg** [comment]
Okay, there were a few different issues, and all important ones:
1. First, if a window was restored when launching the app, it opened before loading the preferences, which caused it to not be correctly configured and try to handle everything through pin 0 of the Arduino. This has been fixed to ensure preferences are loaded before any window opens.
2. If the software had any problems communicating with the Arduino, it did not update the interface to reflect the problems. This has been updated so that a failed Arduino handshake will result in the Arduino dropdown reverting to its original value.
3. The hard to track down issue was that an update made many months ago to the serial port library used caused problems parsing packets from the Arduino, where the full value of the pin would not always be read. This was causing the triggering problems that I was not able to reproduce that only emerged on your instance, as your wiring was better and actually got the full saturated digital pin. I have an open pull request with the `ORSSerialPort` project to re-enable the better packet parsing, but have temporarily patched the app with my version.

I think this all resolves the issue, but I will run some tests next week to confirm.

**Comment by nathanntg** [comment]
I tested the updates made over the weekend, and they resolve all the identified issues.
